### ISSUE TITLE
Flipper does not flip at edge of screen

### ISSUE THREAD

**Issue by easyaspi314** [dozingcat/Vector-Pinball#105]
If you touch the very edge of the screen, the sound effect will play, the blue rollovers will shift, but the flippers will not flip or do a partial flip. This has caused some unexpected deaths. 

> https://user-images.githubusercontent.com/6258309/156766986-3f38a887-099b-4d37-9cac-a8dbf6a994d0.mp4

**Comment by dozingcat** [comment]
That's interesting, I can get similar behavior. I suspect what's happening is that the OS is trying to avoid "false positive" touches at the edges of the screen because you might just be holding the phone there. If I touch and hold at the edge of the screen, no touch event gets delivered at all. If I tap quickly (as it looks like you were doing in the video), then the OS seems to deliver a touch down event followed nearly immediately by a touch release event. The interval between those two events seems to be much shorter than when you tap away from the edges, which is why the flipper barely moves.

Not sure of the best way to improve this. One possibility might be to enforce a minimum time between activating and deactivating a flipper, so that in the case where an up event comes in just a few milliseconds after the down event, the flipper will still have enough time to go all the way up.

Thanks for the report!

**Comment by dozingcat** [comment]
This is fixed as much as possible in 1.10.0. If you tap the edge of the screen you'll get enough of a flipper activation to move the ball. It will still be delayed, but that seems to be unavoidable given how the OS handles events.
