### ISSUE TITLE
Inconsistent layer order in table 8 with openGL

### ISSUE THREAD

**Issue by balping** [dozingcat/Vector-Pinball#165]
In the new table, the circles in the bottom at the flippers are painted above the flippers when they are filled and under the flippers when they are unfilled. 

| Above the flipper         | Below the flipper     |
|--------------|-----------|
| ![filled](https://github.com/dozingcat/Vector-Pinball/assets/5840038/81b5dd85-7c26-465d-aff5-b5656bc18549)  | ![unfilled](https://github.com/dozingcat/Vector-Pinball/assets/5840038/23fe3a46-5728-42b6-a564-f08c78e621de) |

I think in both cases the circles should be below the flippers.

This only happens with openGL renderer, when rendering with CanvasFieldView the circles are rendered as expected.

**Comment by dozingcat** [comment]
Good find! The problem is that the OpenGL renderer first draws all lines (including circle outlines, which are just a bunch of line segments), and then all filled circles, so circles always appear on top of lines even when they shouldn't. Surprisingly this didn't cause any problems until the newest table. I'll fix it in the next release.
